"""Repository Intelligence contracts and deterministic helpers."""

from autoad_researcher.repository_intelligence.control_models import AnalysisControlSignal
from autoad_researcher.repository_intelligence.evidence_models import (
    EvidenceIndexRecord,
    EvidenceRef,
    FileEvidenceRef,
    RepositoryIdentityEvidenceRef,
    UserInputEvidenceRef,
    WebEvidenceRef,
)
from autoad_researcher.repository_intelligence.evidence import (
    ActiveRepositoryContext,
    EvidenceMiddlewareError,
    FileEvidenceRequest,
    append_evidence,
    create_file_evidence,
    create_repository_identity_evidence,
    read_evidence_index,
)
from autoad_researcher.repository_intelligence.harness import (
    AnalysisTransitionDecision,
    RepositoryIntelligenceHarness,
    StageEntryRecord,
    decide_analysis_transition,
    default_repository_tool_registry,
    resume_fingerprint,
)
from autoad_researcher.repository_intelligence.model_routing import (
    ModelProfile,
    ModelRoutePurpose,
    ModelRouter,
    ModelRoutingDecision,
    ModelSmokeTests,
    RepositoryModelConfig,
    append_model_routing_decision,
    load_model_config,
)
from autoad_researcher.repository_intelligence.models import (
    RepositoryAgentBudget,
    RepositoryArtifactPaths,
    RepositoryCandidate,
    RepositoryClaim,
    RepositoryIntelligenceRequest,
    RepositoryIntelligenceResult,
    RepositoryResolution,
    RepositorySource,
    SubmoduleRecord,
)
from autoad_researcher.repository_intelligence.skills import (
    LoadedSkillRecord,
    LoadedSkillsAudit,
    RepositorySkill,
    RepositorySkillFrontmatter,
    SkillLoadError,
    load_required_skill,
    load_skill_file,
    should_load_stage_skill,
    write_loaded_skills,
)

__all__ = [
    "AnalysisControlSignal",
    "AnalysisTransitionDecision",
    "ActiveRepositoryContext",
    "EvidenceIndexRecord",
    "EvidenceMiddlewareError",
    "EvidenceRef",
    "FileEvidenceRequest",
    "FileEvidenceRef",
    "RepositoryAgentBudget",
    "RepositoryArtifactPaths",
    "RepositoryCandidate",
    "RepositoryClaim",
    "RepositoryIntelligenceHarness",
    "RepositoryIdentityEvidenceRef",
    "RepositoryIntelligenceRequest",
    "RepositoryIntelligenceResult",
    "RepositoryModelConfig",
    "RepositoryResolution",
    "RepositorySource",
    "LoadedSkillRecord",
    "LoadedSkillsAudit",
    "ModelProfile",
    "ModelRoutePurpose",
    "ModelRouter",
    "ModelRoutingDecision",
    "ModelSmokeTests",
    "RepositorySkill",
    "RepositorySkillFrontmatter",
    "SkillLoadError",
    "StageEntryRecord",
    "SubmoduleRecord",
    "UserInputEvidenceRef",
    "WebEvidenceRef",
    "append_evidence",
    "append_model_routing_decision",
    "create_file_evidence",
    "create_repository_identity_evidence",
    "decide_analysis_transition",
    "default_repository_tool_registry",
    "load_model_config",
    "load_required_skill",
    "load_skill_file",
    "read_evidence_index",
    "resume_fingerprint",
    "should_load_stage_skill",
    "write_loaded_skills",
]
