"""AutoAD schema 定义。

所有阶段产物的 Pydantic 数据模型集中于此。
harness、pipeline、storage 等模块不应在各自目录内重复定义 schema。
"""

from autoad_researcher.schemas.approvals import Stage3Approval
from autoad_researcher.schemas.artifacts import ArtifactReferenceV2, ResolvedArtifact
from autoad_researcher.schemas.execution import (
    AttemptIdentitySnapshot,
    AttemptOutcome,
    AttemptRecord,
    ExecutionManifest,
    ExecutionUnitPlan,
    ExecutionUnitRecord,
    ExecutionUnitResourceLedger,
    ExecutionUnitStatus,
    ExecutionStatus,
    ExperimentExecutionHandoff,
    FailureClassification,
    IntakeCheck,
    MatrixCoverageReport,
    OverallExecutionStatus,
    PlannedArtifactBinding,
    PlannedArtifactProduction,
    ProducedArtifactRecord,
    ResolvedArtifactBinding,
    ResourceUsageReport,
    RetryDecision,
    RetryIdentity,
    RunnerIntakeReport,
    RunnerIntakeRequest,
    TerminalReason,
    WorkspaceExecutionRef,
)
from autoad_researcher.schemas.results_analysis import (
    AggregatedMetricComparison,
    AggregatedMetricKey,
    BaselineMetricSource,
    BaselineResourceAggregate,
    BundleBudgetAssessment,
    BundleResourceAggregate,
    CurrentRunBaselineMetricRef,
    EvidenceSufficiency,
    FailureAnalysis,
    IdeaSupportConclusion,
    MetricObservationKey,
    NextRunProposal,
    PairedMetricObservation,
    Reflection,
    ReplicationGroup,
    ReplicationPairEvidence,
    ReportFacts,
    ReproducibilityInterpretation,
    ResolvedMetricEvidence,
    ResolvedValidityEvidence,
    ResourceComparisonReport,
    ResourceDelta,
    ReusedBaselineMetricRef,
    ValidityInterpretation,
    VariantBudgetAssessment,
    VariantResourceAggregate,
    VariantScientificConclusion,
)
from autoad_researcher.schemas.benchmark import (
    BenchmarkDataset,
    BenchmarkDatasetAcquisition,
    BenchmarkEvaluationContract,
    BenchmarkMetric,
    BenchmarkReproducibility,
    BenchmarkRepository,
    BenchmarkSafety,
    InternalBenchmarkCase,
)
from autoad_researcher.schemas.clarification import (
    ArtifactReference,
    ClarificationCategory,
    ClarificationContext,
    ClarificationQuestion,
    ClarificationStatus,
    ClarifiedTask,
    KnownFact,
    MissingInformation,
    QuestionAnswerType,
)
from autoad_researcher.schemas.decisions import (
    ConfirmedDecision,
    DecisionCandidate,
    DecisionCandidateSource,
    DecisionConfirmationSource,
    DecisionEvidence,
)
from autoad_researcher.schemas.experiment import ExperimentPlan
from autoad_researcher.schemas.experiment_planning import (
    AcceleratorRequirement,
    AllSeedsDegradedCondition,
    AllSeedsImprovedCondition,
    AlwaysCondition,
    ArtifactManifest,
    ArtifactProduction,
    ArtifactRequirement,
    AssetRequirement,
    BaselineExecutionPolicy,
    BaselineResultRef,
    BudgetDecision,
    BudgetRevisionOption,
    DatasetPartitionRef,
    DecisionConditionType,
    DecisionConditionUnion,
    DependencyRequirement,
    EntryResourceEstimate,
    ExperimentBundleResourceBudget,
    ExperimentMatrix,
    ExperimentPlanningInput,
    ExperimentPlanValidationIssue,
    ExperimentPlanValidationReport,
    ExperimentPlannerHandoff,
    ExperimentTrialSpecs,
    ExperimentResolvableDimension,
    ExperimentVariantInput,
    ExperimentalResolutionPlan,
    ExperimentalResolutionPlans,
    HyperparameterPlan,
    HyperparameterSpec,
    IncompletePairsCondition,
    InterfaceConstraint,
    InvariantResult,
    ManifestEntry,
    MatrixEntry,
    MatrixInputBinding,
    MeanDegradedAboveThresholdCondition,
    MeanImprovedAboveThresholdCondition,
    MixedDirectionCondition,
    NoNanCriterion,
    OperationalGuard,
    OperationalGuardPolicy,
    PLANNING_ARTIFACT_PATHS,
    PlanningInputRefs,
    PreparationPhase,
    RangeCriterion,
    ResolutionCriterion,
    ResolutionOutcome,
    ResourceBudget,
    ResourceLimits,
    ScientificConclusion,
    ScientificDecisionRule,
    SearchBudget,
    SearchParameter,
    SeedMetric,
    ShapeMatchCriterion,
    SharedExperimentProtocol,
    StatisticalAnalysisPlan,
    SupplementalEvaluationRefs,
    ThresholdCriterion,
    TrialIntent,
    ValidatedArtifactRef,
    VariantImplementationRequirements,
    VariantResourceSummary,
    VariantTrialSpec,
    WithinEquivalenceMarginCondition,
)
from autoad_researcher.schemas.ideas import (
    EstimatedIdeaCost,
    IdeaCandidate,
    IdeaContext,
    IdeaGenerationResult,
    IdeaMode,
    IdeaRouteDecision,
)
from autoad_researcher.schemas.intake import (
    InputTask,
    SourceEntry,
    SourceKind,
    SourceManifest,
)
from autoad_researcher.schemas.patch import PatchPlan
from autoad_researcher.schemas.readers import (
    EvidenceReference,
    KnowledgeState,
    PaperSummary,
    RepositorySummary,
)

__all__ = [
    # Approvals
    "Stage3Approval",
    # Artifact references
    "ArtifactReferenceV2",
    # Artifacts
    "ArtifactReferenceV2",
    # Benchmark
    "BenchmarkDataset",
    "BenchmarkDatasetAcquisition",
    "BenchmarkEvaluationContract",
    "BenchmarkMetric",
    "BenchmarkReproducibility",
    "BenchmarkRepository",
    "BenchmarkSafety",
    # Clarification
    "ArtifactReference",
    "ClarificationCategory",
    "ClarificationContext",
    "ClarificationQuestion",
    "ClarificationStatus",
    "ClarifiedTask",
    "KnownFact",
    "MissingInformation",
    "QuestionAnswerType",
    # Decisions
    "ConfirmedDecision",
    "DecisionCandidate",
    "DecisionCandidateSource",
    "DecisionConfirmationSource",
    "DecisionEvidence",
    # Experiment (legacy)
    "ExperimentPlan",
    # Experiment planning — 3.5 schemas
    "AcceleratorRequirement",
    "AllSeedsDegradedCondition",
    "AllSeedsImprovedCondition",
    "AlwaysCondition",
    "ArtifactManifest",
    "ArtifactProduction",
    "ArtifactRequirement",
    "AssetRequirement",
    "BaselineExecutionPolicy",
    "BaselineResultRef",
    "BudgetDecision",
    "BudgetRevisionOption",
    "DatasetPartitionRef",
    "DecisionConditionType",
    "DecisionConditionUnion",
    "DependencyRequirement",
    "EntryResourceEstimate",
    "ExperimentBundleResourceBudget",
    "ExperimentMatrix",
    "ExperimentPlanningInput",
    "ExperimentPlanValidationIssue",
    "ExperimentPlanValidationReport",
    "ExperimentPlannerHandoff",
    "ExperimentTrialSpecs",
    "ExperimentResolvableDimension",
    "ExperimentVariantInput",
    "ExperimentalResolutionPlan",
    "ExperimentalResolutionPlans",
    "HyperparameterPlan",
    "HyperparameterSpec",
    "IncompletePairsCondition",
    "InterfaceConstraint",
    "InvariantResult",
    "ManifestEntry",
    "MatrixEntry",
    "MatrixInputBinding",
    "MeanDegradedAboveThresholdCondition",
    "MeanImprovedAboveThresholdCondition",
    "MixedDirectionCondition",
    "NoNanCriterion",
    "OperationalGuard",
    "OperationalGuardPolicy",
    "PLANNING_ARTIFACT_PATHS",
    "PlanningInputRefs",
    "PreparationPhase",
    "RangeCriterion",
    "ResolutionCriterion",
    "ResolutionOutcome",
    "ResourceBudget",
    "ResourceLimits",
    "ScientificConclusion",
    "ScientificDecisionRule",
    "SearchBudget",
    "SearchParameter",
    "SeedMetric",
    "ShapeMatchCriterion",
    "SharedExperimentProtocol",
    "StatisticalAnalysisPlan",
    "SupplementalEvaluationRefs",
    "ThresholdCriterion",
    "TrialIntent",
    "ValidatedArtifactRef",
    "VariantImplementationRequirements",
    "VariantResourceSummary",
    "VariantTrialSpec",
    "WithinEquivalenceMarginCondition",
    # Ideas
    "EstimatedIdeaCost",
    "IdeaCandidate",
    "IdeaContext",
    "IdeaGenerationResult",
    "IdeaMode",
    "IdeaRouteDecision",
    # Intake
    "InputTask",
    "SourceEntry",
    "SourceKind",
    "SourceManifest",
    # Patch
    "PatchPlan",
    # Readers
    "EvidenceReference",
    "KnowledgeState",
    "PaperSummary",
    "RepositorySummary",
    # Artifacts
    "ResolvedArtifact",
    # Execution — 3.8 schemas
    "AttemptIdentitySnapshot",
    "AttemptOutcome",
    "AttemptRecord",
    "ExecutionManifest",
    "ExecutionUnitPlan",
    "ExecutionUnitRecord",
    "ExecutionUnitResourceLedger",
    "ExecutionUnitStatus",
    "ExecutionStatus",
    "ExperimentExecutionHandoff",
    "FailureClassification",
    "IntakeCheck",
    "MatrixCoverageReport",
    "OverallExecutionStatus",
    "PlannedArtifactBinding",
    "PlannedArtifactProduction",
    "ProducedArtifactRecord",
    "ResolvedArtifactBinding",
    "ResourceUsageReport",
    "RetryDecision",
    "RetryIdentity",
    "RunnerIntakeReport",
    "RunnerIntakeRequest",
    "TerminalReason",
    "WorkspaceExecutionRef",
    # Results analysis — 3.9 schemas
    "AggregatedMetricComparison",
    "AggregatedMetricKey",
    "BaselineMetricSource",
    "BaselineResourceAggregate",
    "BundleBudgetAssessment",
    "BundleResourceAggregate",
    "CurrentRunBaselineMetricRef",
    "EvidenceSufficiency",
    "FailureAnalysis",
    "IdeaSupportConclusion",
    "MetricObservationKey",
    "NextRunProposal",
    "PairedMetricObservation",
    "Reflection",
    "ReplicationGroup",
    "ReplicationPairEvidence",
    "ReportFacts",
    "ReproducibilityInterpretation",
    "ResolvedMetricEvidence",
    "ResolvedValidityEvidence",
    "ResourceComparisonReport",
    "ResourceDelta",
    "ReusedBaselineMetricRef",
    "ValidityInterpretation",
    "VariantBudgetAssessment",
    "VariantResourceAggregate",
    "VariantScientificConclusion",
]

# Resolve forward references: ClarifiedTask → DecisionCandidate, ConfirmedDecision
ClarifiedTask.model_rebuild()
