"""AutoAD schema 定义。

所有阶段产物的 Pydantic 数据模型集中于此。
harness、pipeline、storage 等模块不应在各自目录内重复定义 schema。
"""

from autoad_researcher.schemas.baseline_architecture import (
    ArchitectureComponent,
    BaselineArchitectureContract,
    ExecutionPhaseContract,
    InterfaceSpec,
    ModificationHook,
    TensorAxis,
    TensorSpec,
)
from autoad_researcher.schemas.benchmark import (
    BenchmarkDataset,
    BenchmarkDatasetAcquisition,
    BenchmarkEvaluationContract,
    BenchmarkMetric,
    BenchmarkReproducibility,
    BenchmarkRepository,
    BenchmarkSafety,
    InternalBenchmarkCase,
)
from autoad_researcher.schemas.clarification import (
    ArtifactReference,
    ClarificationCategory,
    ClarificationContext,
    ClarificationQuestion,
    ClarificationStatus,
    ClarifiedTask,
    KnownFact,
    MissingInformation,
    QuestionAnswerType,
)
from autoad_researcher.schemas.decisions import (
    ConfirmedDecision,
    DecisionCandidate,
    DecisionCandidateSource,
    DecisionConfirmationSource,
    DecisionEvidence,
)
from autoad_researcher.schemas.experiment import ExperimentPlan
from autoad_researcher.schemas.ideas import (
    EstimatedIdeaCost,
    IdeaCandidate,
    IdeaContext,
    IdeaGenerationResult,
    IdeaMode,
    IdeaRouteDecision,
)
from autoad_researcher.schemas.intake import (
    InputTask,
    SourceEntry,
    SourceKind,
    SourceManifest,
)
from autoad_researcher.schemas.patch import PatchPlan
from autoad_researcher.schemas.patch_planning import (
    ApprovalDecision,
    ApprovalRequest,
    ChangedFileEntry,
    CheckResult,
    NarrowRepositoryReadRequest,
    PatchApplicationManifest,
    PatchApplicationPreflightResult,
    PatchConflictAnalysis,
    PatchConflictGroup,
    PatchExecutionResult,
    PatchPayload,
    PatchPlanValidationIssue,
    PatchPlanValidationReport,
    PatchRunnerHandoff,
    PlannedConfigurationChange,
    PlannedDependencyChange,
    PlannedRepositoryChange,
    PlannedTestChange,
    PostPatchValidationReport,
    RepositoryChangePlan,
    RepositoryScopeExpansionRequired,
    RollbackManifest,
    SymbolContractDelta,
    SymbolQuery,
    ValidationCommand,
    VariantWorkspacePlan,
    WorkspaceApprovalSummary,
    compute_canonical_plan_sha256,
)
from autoad_researcher.schemas.readers import (
    EvidenceReference,
    KnowledgeState,
    PaperSummary,
    RepositorySummary,
)
from autoad_researcher.schemas.transfer_design import (
    AcceptedRisk,
    AlignableScope,
    AlignmentEntry,
    AlignmentStatus,
    CLASSIFICATION_RULES,
    DIMENSION_POLICY,
    CompatibilityDimension,
    CompatibilityStatus,
    ConstraintRef,
    ConstraintStrength,
    DerivedClaim,
    DimensionJudgment,
    EvidenceStrategy,
    HookBinding,
    IdeaAspectRef,
    IdeaContract,
    IdeaContractCore,
    IdeaTransferAnalysis,
    IdeaTransferBudget,
    IdeaTransferDesignHandoff,
    IdeaTransferValidationReport,
    ImplementationVariant,
    InterfaceContractDelta,
    PaperGroundedIdeaContract,
    PaperReanalysisRequest,
    RegimeChange,
    RejectedVariant,
    RepositoryReanalysisRequest,
    ResolutionClass,
    RiskRecord,
    SelectedVariant,
    SpawnChildRunRequest,
    StateChangeDescription,
    TensorContractDelta,
    TransferConstraint,
    TransferResumeFingerprint,
    TransferStatus,
    TransferValidationIssue,
    UnresolvedDimension,
    UserProvidedIdeaContract,
    VariantRiskReport,
    VariantSelection,
    VariantTransferAnalysis,
    compute_variant_risk,
    derive_variant_status,
    violates_confirmed_constraint,
)

__all__ = [
    # Baseline architecture
    "ArchitectureComponent",
    "BaselineArchitectureContract",
    "ExecutionPhaseContract",
    "InterfaceSpec",
    "ModificationHook",
    "TensorAxis",
    "TensorSpec",
    # Benchmark
    "BenchmarkDataset",
    "BenchmarkDatasetAcquisition",
    "BenchmarkEvaluationContract",
    "BenchmarkMetric",
    "BenchmarkReproducibility",
    "BenchmarkRepository",
    "BenchmarkSafety",
    # Clarification
    "ArtifactReference",
    "ClarificationCategory",
    "ClarificationContext",
    "ClarificationQuestion",
    "ClarificationStatus",
    "ClarifiedTask",
    "KnownFact",
    "MissingInformation",
    "QuestionAnswerType",
    # Decisions
    "ConfirmedDecision",
    "DecisionCandidate",
    "DecisionCandidateSource",
    "DecisionConfirmationSource",
    "DecisionEvidence",
    # Experiment
    "ExperimentPlan",
    # Ideas
    "EstimatedIdeaCost",
    "IdeaCandidate",
    "IdeaContext",
    "IdeaGenerationResult",
    "IdeaMode",
    "IdeaRouteDecision",
    # Intake
    "InputTask",
    "SourceEntry",
    "SourceKind",
    "SourceManifest",
    # Patch
    "PatchPlan",
    # Patch planning — 3.6/3.7 schemas
    "ApprovalDecision",
    "ApprovalRequest",
    "ChangedFileEntry",
    "CheckResult",
    "NarrowRepositoryReadRequest",
    "PatchApplicationManifest",
    "PatchApplicationPreflightResult",
    "PatchConflictAnalysis",
    "PatchConflictGroup",
    "PatchExecutionResult",
    "PatchPayload",
    "PatchPlanValidationIssue",
    "PatchPlanValidationReport",
    "PatchRunnerHandoff",
    "PlannedConfigurationChange",
    "PlannedDependencyChange",
    "PlannedRepositoryChange",
    "PlannedTestChange",
    "PostPatchValidationReport",
    "RepositoryChangePlan",
    "RepositoryScopeExpansionRequired",
    "RollbackManifest",
    "SymbolContractDelta",
    "SymbolQuery",
    "ValidationCommand",
    "VariantWorkspacePlan",
    "WorkspaceApprovalSummary",
    "compute_canonical_plan_sha256",
    # Readers
    "EvidenceReference",
    "KnowledgeState",
    "PaperSummary",
    "RepositorySummary",
    # Transfer design — schemas
    "AcceptedRisk",
    "AlignableScope",
    "AlignmentEntry",
    "AlignmentStatus",
    "CLASSIFICATION_RULES",
    "CompatibilityDimension",
    "CompatibilityStatus",
    "ConstraintRef",
    "ConstraintStrength",
    "DerivedClaim",
    "DimensionJudgment",
    "DIMENSION_POLICY",
    "EvidenceStrategy",
    "HookBinding",
    "IdeaAspectRef",
    "IdeaContract",
    "IdeaContractCore",
    "IdeaTransferAnalysis",
    "IdeaTransferBudget",
    "IdeaTransferDesignHandoff",
    "IdeaTransferValidationReport",
    "ImplementationVariant",
    "InterfaceContractDelta",
    "InternalBenchmarkCase",
    "PaperGroundedIdeaContract",
    "PaperReanalysisRequest",
    "RegimeChange",
    "RejectedVariant",
    "RepositoryReanalysisRequest",
    "ResolutionClass",
    "RiskRecord",
    "SelectedVariant",
    "SpawnChildRunRequest",
    "StateChangeDescription",
    "TensorContractDelta",
    "TransferConstraint",
    "TransferResumeFingerprint",
    "TransferStatus",
    "TransferValidationIssue",
    "UnresolvedDimension",
    "UserProvidedIdeaContract",
    "VariantRiskReport",
    "VariantSelection",
    "VariantTransferAnalysis",
    # Transfer design — functions
    "compute_variant_risk",
    "derive_variant_status",
    "violates_confirmed_constraint",
]

# Resolve forward references: ClarifiedTask → DecisionCandidate, ConfirmedDecision
ClarifiedTask.model_rebuild()
