"""Generic Tool Foundation contracts."""

from autoad_researcher.tools.contracts import ActiveRepositoryContext, ToolContext, ToolResult, ToolSpec
from autoad_researcher.tools.deferred import (
    LoadedToolRecord,
    StageToolLoad,
    initial_tool_specs,
    load_stage_tool_specs,
)
from autoad_researcher.tools.filesystem import (
    FilesystemEntry,
    FilesystemReadRequest,
    FilesystemRequest,
    FilesystemSearchMatch,
    FilesystemSearchRequest,
    FilesystemStat,
    FilesystemToolError,
    FilesystemToolResult,
    filesystem_list,
    filesystem_read,
    filesystem_search,
    filesystem_stat,
    filesystem_tool_spec,
)
from autoad_researcher.tools.permissions import (
    PermissionDecision,
    PermissionDecisionRecord,
    PermissionEngine,
    PermissionProfile,
    PermissionRequest,
    append_permission_decision,
    default_repository_permission_engine,
)
from autoad_researcher.tools.process import (
    ProcessToolOutput,
    ProcessToolRequest,
    ProcessToolResult,
    process_tool_spec,
    run_process_tool,
)
from autoad_researcher.tools.providers import (
    GitHubCommitRef,
    GitHubFileContent,
    GitHubReadProvider,
    GitHubRepositoryMetadata,
    ProviderError,
    RecordedWebSearchProvider,
    SecureWebFetchProvider,
    WebFetchResult,
    WebSearchResult,
)
from autoad_researcher.tools.registry import ToolRegistry

__all__ = [
    "LoadedToolRecord",
    "ActiveRepositoryContext",
    "PermissionDecision",
    "PermissionDecisionRecord",
    "PermissionEngine",
    "PermissionProfile",
    "PermissionRequest",
    "ProcessToolOutput",
    "ProcessToolRequest",
    "ProcessToolResult",
    "ProviderError",
    "RecordedWebSearchProvider",
    "SecureWebFetchProvider",
    "StageToolLoad",
    "ToolContext",
    "ToolRegistry",
    "ToolResult",
    "ToolSpec",
    "GitHubCommitRef",
    "GitHubFileContent",
    "GitHubReadProvider",
    "GitHubRepositoryMetadata",
    "WebFetchResult",
    "WebSearchResult",
    "FilesystemEntry",
    "FilesystemReadRequest",
    "FilesystemRequest",
    "FilesystemSearchMatch",
    "FilesystemSearchRequest",
    "FilesystemStat",
    "FilesystemToolError",
    "FilesystemToolResult",
    "append_permission_decision",
    "default_repository_permission_engine",
    "filesystem_list",
    "filesystem_read",
    "filesystem_search",
    "filesystem_stat",
    "filesystem_tool_spec",
    "initial_tool_specs",
    "load_stage_tool_specs",
    "process_tool_spec",
    "run_process_tool",
]
