[browser]
gatherUsageStats = false

[theme]
base = "dark"

[client]
toolbarMode = "minimal"

[server]
enableCORS = true
enableXsrfProtection = false
enableWebsocketCompression = false
headless = true
